name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build MkDocs site
        working-directory: mkdocs
        run: uv run --no-project --with mkdocs-material==9.7.6 mkdocs build
